{
 "title": "Environment Monitors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "watchdog",
    "label": "Watchdog Device",
    "query": "label_values(watchdog_TempF, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Water in Front AC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "watchdog_IO1{job=\"$watchdog\"}",
     "legendFormat": "{{$deviceName}} Water Detected %"
    }
   ]
  },
  {
   "title": "Water in Rear AC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "watchdog_IO2{job=\"$watchdog\"}",
     "legendFormat": "{{$deviceName}} Water Detected %"
    }
   ]
  },
  {
   "title": "Water in Floor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "watchdog_IO3{job=\"$watchdog\"}",
     "legendFormat": "{{$deviceName}} Water Detected %"
    }
   ]
  },
  {
   "title": "Rear AC Temp(F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watchdog_TempF{job=\"$watchdog\", deviceName=~\"Rear.*\"}",
     "legendFormat": "{{deviceName}} Temp(F)"
    }
   ]
  },
  {
   "title": "Front AC Temp(F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watchdog_TempF{job=\"$watchdog\", deviceName=\"Front Room A/C\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "watchdog_Humidity{job=~\"$watchdog\"}",
     "legendFormat": "{{deviceName}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "watchdog_TempF{job=\"$watchdog\"}",
     "legendFormat": "{{deviceName}}"
    }
   ]
  },
  {
   "title": "Sound",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "watchdog_Sound{job=\"$watchdog\"}",
     "legendFormat": "{{$devicename}} Sound Level"
    }
   ]
  },
  {
   "title": "Airflow",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "flowcfm" }
   ],
   "targets": [
    {
     "expr": "watchdog_Airflow{job=\"$watchdog\"}",
     "legendFormat": "{{$deviceName}} AirFlow"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "watchdog_Light{job=\"$watchdog\"}",
     "legendFormat": "{{$deviceName}} Light Level"
    }
   ]
  }
 ]
}